package com.abhi.mymoney
import android.app.*;import android.content.*;import android.os.*;import android.graphics.Typeface;import android.widget.*;import java.util.*
class FriendsActivity:Activity(){
 lateinit var list:LinearLayout
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_friends);list=findViewById(R.id.friendList);findViewById<Button>(R.id.backBtn).setOnClickListener{finish()};findViewById<Button>(R.id.addFriendBtn).setOnClickListener{add()};findViewById<Button>(R.id.addFriendBottom).setOnClickListener{add()};render()}
 override fun onResume(){super.onResume();if(::list.isInitialized)render()}
 fun money(v:Double)="₹"+String.format(Locale.US,"%.2f",v)
 fun render(){list.removeAllViews();val fs=MoneyStore.friends(this);val names=fs.map{it.name}.distinctBy{MoneyStore.key(it)}.sortedBy{it.lowercase()};if(names.isEmpty()){TextView(this).also{it.text="No friends yet.\nAdd a payment to start.";it.textSize=16f;it.setPadding(12,40,12,40);list.addView(it)};return};names.forEach{name->val due=MoneyStore.due(this,name);val all=fs.filter{MoneyStore.key(it.name)==MoneyStore.key(name)};val paid=all.filter{it.type.startsWith("I paid")}.sumOf{it.amount};val got=all.filter{!it.type.startsWith("I paid")}.sumOf{it.amount};val card=LinearLayout(this);card.orientation=LinearLayout.VERTICAL;card.setPadding(18,14,18,14);card.setBackgroundResource(R.drawable.card_bg);val title=TextView(this);title.text=name;title.textSize=18f;title.setTypeface(null,Typeface.BOLD);val totals=TextView(this);totals.text="You paid ${money(paid)}   •   They paid you ${money(got)}";val d=TextView(this);d.text=if(due>0)"YOU WILL RECEIVE  ${money(due)}" else if(due<0)"YOU OWE  ${money(-due)}" else "SETTLED  ₹0.00";d.textSize=15f;d.setTypeface(null,Typeface.BOLD);val open=Button(this);open.text="View details";open.setOnClickListener{startActivity(Intent(this,FriendDetailActivity::class.java).putExtra("name",name))};card.addView(title);card.addView(totals);card.addView(d);card.addView(open);card.layoutParams=LinearLayout.LayoutParams(-1,-2).apply{bottomMargin=12};list.addView(card)}}
 fun add(){FriendDetailActivity.dialog(this,null){render()}}
}
